create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (length(trim(full_name)) > 0),
  username text not null check (length(trim(username)) > 0),
  role text not null check (role in ('Manager', 'Staff')),
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_username_lower_idx
  on public.profiles (lower(username));

create table if not exists public.restaurant_operations (
  id integer primary key default 1 check (id = 1),
  is_open boolean not null default false,
  operation_cycle integer not null default 0,
  business_date date not null default current_date,
  opened_at timestamptz,
  opened_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.restaurant_operations (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null check (length(trim(title)) > 0),
  description text not null default '',
  assigned_to uuid references public.profiles(id) on delete set null,
  status text not null default 'To Do' check (status in ('To Do', 'In Progress', 'Done')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.tasks
  add column if not exists priority text not null default 'Medium',
  add column if not exists category text not null default 'Other',
  add column if not exists due_date date,
  add column if not exists business_date date not null default current_date,
  add column if not exists archived_at timestamptz,
  add column if not exists operation_cycle integer not null default 1;

alter table public.tasks drop constraint if exists tasks_priority_check;
alter table public.tasks add constraint tasks_priority_check
  check (priority in ('Low', 'Medium', 'High'));

alter table public.tasks drop constraint if exists tasks_category_check;
alter table public.tasks add constraint tasks_category_check
  check (category in ('Kitchen Preparation', 'Cleaning', 'Inventory', 'Service Setup', 'Maintenance', 'Other'));

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  user_name text not null,
  action text not null check (length(trim(action)) > 0),
  task_title text,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_closings (
  id bigint generated by default as identity primary key,
  business_date date not null unique,
  manager_id uuid not null references public.profiles(id) on delete restrict,
  manager_name text not null,
  total_tasks integer not null default 0,
  completed_tasks integer not null default 0,
  carried_tasks integer not null default 0,
  overdue_tasks integer not null default 0,
  closed_at timestamptz not null default now()
);

alter table public.daily_closings
  add column if not exists issue_tasks integer not null default 0,
  add column if not exists no_issue_tasks integer not null default 0,
  add column if not exists operation_cycle integer not null default 1,
  add column if not exists opened_at timestamptz;

alter table public.daily_closings
  drop constraint if exists daily_closings_business_date_key;

create table if not exists public.daily_task_templates (
  id uuid primary key default gen_random_uuid(),
  title text not null check (length(trim(title)) > 0),
  description text not null default '',
  assigned_to uuid references public.profiles(id) on delete set null,
  priority text not null default 'Medium' check (priority in ('Low', 'Medium', 'High')),
  category text not null default 'Other' check (category in ('Kitchen Preparation', 'Cleaning', 'Inventory', 'Service Setup', 'Maintenance', 'Other')),
  due_offset_days integer not null default 0 check (due_offset_days between 0 and 30),
  active boolean not null default true,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.tasks
  add column if not exists source_template_id uuid references public.daily_task_templates(id) on delete set null;

drop index if exists public.tasks_daily_template_date_idx;
create unique index if not exists tasks_daily_template_cycle_idx
  on public.tasks (source_template_id, business_date, operation_cycle)
  where source_template_id is not null;

create table if not exists public.closing_task_reviews (
  id bigint generated by default as identity primary key,
  closing_id bigint not null references public.daily_closings(id) on delete cascade,
  business_date date not null,
  task_id uuid,
  task_title text not null,
  assigned_to uuid,
  assigned_name text not null default 'Unassigned',
  original_status text not null check (original_status in ('To Do', 'In Progress', 'Done')),
  outcome text not null check (outcome in ('Completed', 'Issue', 'No Issue')),
  note text not null default '',
  manager_id uuid not null references public.profiles(id) on delete restrict,
  manager_name text not null,
  created_at timestamptz not null default now()
);

alter table public.closing_task_reviews
  add column if not exists operation_cycle integer not null default 1;

create schema if not exists private;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, username, role)
  values (
    new.id,
    trim(new.raw_user_meta_data ->> 'full_name'),
    lower(trim(new.raw_user_meta_data ->> 'username')),
    case when new.raw_user_meta_data ->> 'role' = 'Manager' then 'Manager' else 'Staff' end
  );
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

create or replace function private.protect_staff_task_updates()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_role text;
begin
  if pg_trigger_depth() > 1 then
    return new;
  end if;

  -- Allow trusted database maintenance from Supabase SQL Editor or service role.
  -- Normal application users are still checked through public.profiles below.
  if auth.uid() is null and current_user in ('postgres', 'supabase_admin', 'service_role') then
    return new;
  end if;

  select role into v_role
  from public.profiles
  where id = auth.uid();

  -- Managers can update task fields, including archived_at during Close Today.
  if v_role = 'Manager' then
    return new;
  end if;

  -- Staff users may only update task status.
  if v_role = 'Staff' then
    if
      new.title is distinct from old.title or
      new.description is distinct from old.description or
      new.assigned_to is distinct from old.assigned_to or
      new.priority is distinct from old.priority or
      new.category is distinct from old.category or
      new.due_date is distinct from old.due_date or
      new.business_date is distinct from old.business_date or
      new.operation_cycle is distinct from old.operation_cycle or
      new.source_template_id is distinct from old.source_template_id or
      new.archived_at is distinct from old.archived_at or
      new.created_by is distinct from old.created_by or
      new.created_at is distinct from old.created_at
    then
      raise exception 'Staff may only update task status';
    end if;

    return new;
  end if;

  raise exception 'Only managers or assigned staff may update tasks';
end;
$$;

drop trigger if exists protect_staff_task_updates on public.tasks;
create trigger protect_staff_task_updates
  before update on public.tasks
  for each row execute function private.protect_staff_task_updates();

alter table public.profiles enable row level security;
alter table public.restaurant_operations enable row level security;
alter table public.tasks enable row level security;
alter table public.activity_log enable row level security;
alter table public.daily_closings enable row level security;
alter table public.daily_task_templates enable row level security;
alter table public.closing_task_reviews enable row level security;

drop policy if exists "Authenticated users can view profiles" on public.profiles;
create policy "Authenticated users can view profiles"
  on public.profiles for select
  to authenticated
  using (true);

drop policy if exists "Users can view permitted tasks" on public.tasks;
create policy "Users can view permitted tasks"
  on public.tasks for select
  to authenticated
  using (
    (assigned_to = (select auth.uid()) and archived_at is null)
    or exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'Manager'
    )
  );

drop policy if exists "Managers can create tasks" on public.tasks;
create policy "Managers can create tasks"
  on public.tasks for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'Manager'
    )
  );

drop policy if exists "Managers and assigned staff can update tasks" on public.tasks;
create policy "Managers and assigned staff can update tasks"
  on public.tasks for update
  to authenticated
  using (
    assigned_to = (select auth.uid())
    or exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'Manager'
    )
  )
  with check (
    assigned_to = (select auth.uid())
    or exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'Manager'
    )
  );

drop policy if exists "Managers can delete tasks" on public.tasks;
create policy "Managers can delete tasks"
  on public.tasks for delete
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'Manager'
    )
  );

drop policy if exists "Authenticated users can view activity" on public.activity_log;
create policy "Authenticated users can view activity"
  on public.activity_log for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can view operations" on public.restaurant_operations;
create policy "Authenticated users can view operations"
  on public.restaurant_operations for select
  to authenticated
  using (true);

drop policy if exists "Managers can update operations" on public.restaurant_operations;
create policy "Managers can update operations"
  on public.restaurant_operations for update
  to authenticated
  using (
    exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  )
  with check (
    exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  );

drop policy if exists "Users can record own activity" on public.activity_log;
create policy "Users can record own activity"
  on public.activity_log for insert
  to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists "Managers can view closings" on public.daily_closings;
create policy "Managers can view closings"
  on public.daily_closings for select
  to authenticated
  using (
    exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  );

drop policy if exists "Managers can create closings" on public.daily_closings;
create policy "Managers can create closings"
  on public.daily_closings for insert
  to authenticated
  with check (
    manager_id = (select auth.uid())
    and exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  );

drop policy if exists "Managers can manage daily templates" on public.daily_task_templates;
create policy "Managers can manage daily templates"
  on public.daily_task_templates for all
  to authenticated
  using (
    exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  )
  with check (
    created_by = (select auth.uid())
    and exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  );

drop policy if exists "Managers can view closing reviews" on public.closing_task_reviews;
create policy "Managers can view closing reviews"
  on public.closing_task_reviews for select
  to authenticated
  using (
    exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  );

drop policy if exists "Managers can create closing reviews" on public.closing_task_reviews;
create policy "Managers can create closing reviews"
  on public.closing_task_reviews for insert
  to authenticated
  with check (
    manager_id = (select auth.uid())
    and exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'Manager')
  );

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, update on public.restaurant_operations to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;
grant select, insert on public.activity_log to authenticated;
grant usage, select on sequence public.activity_log_id_seq to authenticated;
grant select, insert on public.daily_closings to authenticated;
grant usage, select on sequence public.daily_closings_id_seq to authenticated;
grant select, insert, update, delete on public.daily_task_templates to authenticated;
grant select, insert on public.closing_task_reviews to authenticated;
grant usage, select on sequence public.closing_task_reviews_id_seq to authenticated;
